# Generated by Django 4.0.6 on 2022-07-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile/%Y/%m/%d/', verbose_name='profile image'),
        ),
    ]
