# Generated by Django 4.0.6 on 2022-07-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default=1, max_length=30, verbose_name='nickname'),
            preserve_default=False,
        ),
    ]
