# Generated by Django 4.0.6 on 2022-07-15 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='image/%Y/%m/%d/', verbose_name='게시글 이미지')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_f', to=settings.AUTH_USER_MODEL, verbose_name='게시글 작성자')),
                ('voter', models.ManyToManyField(related_name='voter_f', to=settings.AUTH_USER_MODEL, verbose_name='추천인')),
            ],
            options={
                'db_table': 'feeds',
            },
        ),
    ]
