# Generated by Django 4.0.6 on 2022-07-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feed',
            table='feed',
        ),
    ]
