# Generated by Django 4.0.6 on 2022-07-15 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0002_alter_feed_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL, verbose_name='게시글 작성자'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=models.TextField(verbose_name='게시글 내용'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='답글 내용')),
                ('create_date', models.DateTimeField(verbose_name='생성일')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='답글 작성자')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.feed', verbose_name='답글을 단 게시글')),
                ('voter', models.ManyToManyField(related_name='voter_c', to=settings.AUTH_USER_MODEL, verbose_name='추천인')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
