# Generated by Django 4.0.6 on 2022-07-18 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0003_alter_feed_author_alter_feed_content_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='voter',
            field=models.ManyToManyField(related_name='commentVoters', to=settings.AUTH_USER_MODEL, verbose_name='추천인'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='voter',
            field=models.ManyToManyField(related_name='feedVoters', to=settings.AUTH_USER_MODEL, verbose_name='추천인'),
        ),
    ]
