# Generated by Django 4.0.6 on 2022-07-18 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0004_alter_comment_voter_alter_feed_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='voter',
            field=models.ManyToManyField(related_name='voter_comment', to=settings.AUTH_USER_MODEL, verbose_name='추천인'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='voter',
            field=models.ManyToManyField(related_name='voter_feed', to=settings.AUTH_USER_MODEL, verbose_name='추천인'),
        ),
    ]
